name: MaxDaily
on:
  schedule:
    - cron: '59 12 * * 1-5' 
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir numpy
        pip install --no-cache-dir pandas
        pip install -r requirements.txt  # If you have a requirements file
        
    - name: Display installed packages
      run: pip list
      
    - name: Run Python script
      run: python MaxDaily.py  # Replace with the actual path to your script
