name: MaxDaily
on:
  schedule:
    - cron: '59 12 * * 1-5' 

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.15'  # Specify the Python version you need
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.22.4 pandas==1.4.2
        pip install -r requirements.txt  # If you have a requirements file
        
    - name: Run Python script
      run: python MaxDaily.py  # Replace with the actual path to your script
