name: Append Data to CSV
on:
  schedule:
    # 這裡設定您想要的排程 時區預設是UTC +0
    - cron: '30 14 * * 1-5' 
  # 允許您手動從 Actions 頁面觸發此 workflow，方便測試
  workflow_dispatch:
    
jobs:
  # run-script:
  update-csv-file:
    runs-on: ubuntu-latest
    
    # 核心步驟：授予 workflow 寫入 repository 的權限
    permissions:
      contents: write
  
    steps:
    - name: Check out repository # 將repository程式碼 checkout 到 runner 環境
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0  # 完整拉取歷史，避免 fetch 問題
      
    - name: Set up Python # 設定 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script # 執行腳本並將輸出附加到 CSV 檔案(使用 `>>` 運算子來append)
      run: python SddScrawler.py >> tblMkt.csv

    - name: Pull latest changes
      run: |
        git config --global user.name "排程自動"
        git config --global user.email "hhpedo@gmail.com"
        git pull origin main --rebase

    - name: Push changes
      run: |
        
        
        if ! git diff --staged --quiet; then
          git commit -m "Automated CSV update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "無異動故沒commit"
        fi
          
