name: Append Data to CSV
on:
  schedule:
    # 這裡設定您想要的排程 時區預設是UTC +0
    - cron: '30 14 * * 1-5' 
  # 允許您手動從 Actions 頁面觸發此 workflow，方便測試
  workflow_dispatch:
    
jobs:
  # run-script:
  update-csv-file:
    runs-on: ubuntu-latest
    
    # 核心步驟：授予 workflow 寫入 repository 的權限
    permissions:
      contents: write
  
    steps:
    - name: Check out repository # 將repository程式碼 checkout 到 runner 環境
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 確保取得完整歷史記錄
        
    - name: Set up Python # 設定 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script # 執行腳本並將輸出附加到 CSV 檔案(使用 `>>` 運算子來append)
      run: python SddScrawler.py >> tblMkt.csv
        
    - name: Commit and push if it changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "已寫入: data for $(date +'%Y-%m-%d')"
        file_pattern: tblMkt.csv
        commit_user_name: 排程自動
        commit_user_email: hhpedo@gmail.com
