name: test
on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Max step 1 Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Max step 2 Install dependencies
      run: |
        pip install -r requirements.txt; fi
        
    - name:  Max step 3 Run Python Script
      run: |
        python MaxDaily.py
